### ISSUE TITLE
Standard structure for algorithms

### ISSUE THREAD

**Issue by salehhashemi1992** [TheAlgorithms/PHP#118]
first of all, Thank you for this helpful repo.
I've noticed that some algorithms are implemented as functions, while others are implemented using classes and methods.

To maintain consistency, it would be beneficial to define a standard coding style, such as adhering to a specific PSR, namespace, or any other structural guidelines for contributions. This way, all algorithms will follow the same structure, making it easier to understand and contribute to the project.

**Comment by salehhashemi1992** [comment]
it takes a lot of time but I can add autoload and namespaces to the project and also code sniffer

**Comment by darwinz** [comment]
Thanks @salehhashemi1992 .  I don't think we need to go as far as adding autoload and namespaces across the project.  I do agree that keeping a consistent styling is important though.

**Comment by darwinz** [comment]
We've tried to stick to the PSR-12 style guide, found [here](https://xoops.gitbook.io/xoops-modules-cookbook/coding-standards/standards/styleguide)

**Comment by salehhashemi1992** [comment]
So I've done some tweaks here: #122
