### ISSUE TITLE
[Sorting: QuickSort] Empty input validation is incorrect

### ISSUE THREAD

**Issue by anamarijapapic** [TheAlgorithms/PHP#125]
The issue was previously detected in #95, and an attempt to fix it was made in #120.

The code in question:
https://github.com/TheAlgorithms/PHP/blob/618fe7f2b59b3182baf29a372aa82b49dab88a8c/Sorting/QuickSort.php#L12-L15

It should be:
```php
// Return nothing if input is empty
if (empty($input))
{
    return [];
}
```

**Comment by darwinz** [comment]
Oops, you're right.  I missed that in my review.  Thanks, and nice catch!
