### ISSUE TITLE
Add Gitpod Setup

### ISSUE THREAD

**Issue by rohitkbc** [TheAlgorithms/PHP#130]
#### Description
Setup Gitpod environment for running the repository in Gitpod.
    
Add Gitpod ready to code Badge to the README.md file

**Comment by rohitkbc** [comment]
Hi 👋, I am participating in **hacktoberfest**.

**Comment by darwinz** [comment]
Hi @rohitkbc, thanks for raising this issue.  I'd like to see if others in the community are interested in this setup.  I'm unaware of any other projects in the `TheAlgorithms` ecosystem that use Gitpod.  But if there's a real interest from others in using it, we can consider it.

**Comment by darwinz** [comment]
@nikhilkala, are you aware of any other project in the `TheAlgorithms` ecosystem that uses GitPod?

**Comment by rohitkbc** [comment]
Hi @darwinz 👋, others projects in  `TheAlgorithms` are also using gitpod. 
For ex. javascript, python, java etc

**Comment by rohitkbc** [comment]
@darwinz , adding screenshots for reference.

![image](https://github.com/TheAlgorithms/PHP/assets/100275369/9f75462b-d5ad-469c-9e9c-27b40ed95f2c)
![image](https://github.com/TheAlgorithms/PHP/assets/100275369/b016a6dc-6f6d-49dc-9342-14972e747da1)

As shown above, python and java repo in `TheAlgorithms` uses gitpod.

That is why I added gitpod setup for `php` repo.

Please review the PR. ✌️
