### ISSUE TITLE
Quicksort empty clause is not correct

### ISSUE THREAD

**Issue by lcavero** [TheAlgorithms/PHP#95]
Hi, the first clause of quickSort algorithm intended for checking empty inputs is using "isset" function which only checks for variable existence or null. So, if I call quickSort with an empty array ([ ]) this this clause will not work. 

Also, using isset inside this function has not sense because the $input parameter is always defined and it will be always an array (nulls are not allowed with this arguments definition), so it will always evaluate to true.

I think it would be appropriate to use the "empty" function in this case instead.

**Comment by yoctoyu** [comment]
I think it's good comment for strict.
In generally, isset() and count() functions should be used for checking empty array.
In quickSort, if input is "[]" then function will return $input parameter, so I think there is no problem without empty() in this case.

**Comment by lcavero** [comment]
@yoctoyu Ok, but, line 14 is always unreachable whatever the input, so why not remove this clause? It does absolutely nothing in any case.

**Comment by yoctoyu** [comment]
Thanks for your replay @lcavero.
Line 14 is needed for checking whether input is null or not.
If input is null, that line will be executed.

`<?php
$input = null;
if(!isset($input))
{
    echo "Input is null";
    //exit(0);
}

$a = sizeof($input); // if $input is null and no return, fatal error will be occured.
echo "Length is ".$a;
?>`
